- README.md
> correct the repo address in the README

- .travis.yml
- Dockerfile
- Dockerfile.template
- terraform_compliance/main.py
- terraform_compliance/steps/__init__.py
- Added `-v`/`--version` parameter
- Bumped version to 0.3.3
- Moved Dockerfile to Dockerfile.tmp and modifying it dynamically on CD
- Implemented whole CI/CD stack with Travis CI.
- TONs of unnecessary Travis Tests.
- Added few more untaggable resources
- Added few more resource aliases
> Version, CI/CD

- .travis.yml
- terraform_compliance/main.py
A new version bump because of PyPI problem. Mostly this is about CI/CD.
> Fixed travis where docker tags were not correct

- .gitignore
- README.md
- terraform_compliance/main.py
Added git authentication support via using a private ssh key
> Issue 20/git authentication is not supported

- terraform_compliance/main.py
Fixed https://github.com/eerkunt/terraform-compliance/issues/41
> Changed cli() invocations to fix a general problem.

- terraform_compliance/main.py
- terraform_compliance/steps/__init__.py
This PR fixes the issue reported in https://github.com/eerkunt/terraform-compliance/issues/43
> New untaggable resource added

- terraform_compliance/steps/__init__.py
There are some non aws taggable resources:
- route
- main_route_table_association
- egress_only_internet_gateway
> Added some non taggable resources

- terraform_compliance/main.py
- terraform_compliance/steps/__init__.py
As previously I've come across a resource that's untaggable. 
Thanks.
> Adding aws_s3_bucket_policy to list of untaggable resources. 

- CHANGELOG.md
- example/example_01/aws/tags.feature
- requirements.txt
- terraform_compliance/main.py
This PR addresses the issue defined in #110
> Supporting PIPE (|) characters within BDD Scenarios

- terraform_compliance/main.py
- terraform_compliance/steps/steps.py
This problem addresses the issue reported in #106
> Fixed a problem where 'its value must not be null' was not working properly

- terraform_compliance/extensions/terraform.py
- terraform_compliance/main.py
- terraform_compliance/steps/steps.py
This PR addresses the issue reported in #111
> Fixed a problem where some of the data resources defined in configuration section was not distinguished.

- terraform_compliance/common/helper.py
- terraform_compliance/main.py
- terraform_compliance/steps/steps.py
Addresses the issue defined in #90 and #111.
Fixed where some of the values are `False` or `None`.
> None/False fix.

- example/example_01/aws/encryption_at_rest.feature
- example/example_01/aws/encryption_in_flight.feature
- terraform_compliance/main.py
- terraform_compliance/steps/__init__.py
- terraform_compliance/steps/steps.py
I think this new step would takes care of any property including encryption (both at rest and in flight) and any other properties you might want to check to see if they are enabled.
> added new step @then(u'{something:ANY} must be enabled') as a replacement for enable encryption step

- CHANGELOG.md
- setup.py
- terraform_compliance/__init__.py
- terraform_compliance/main.py
> Fix installing from source

- terraform_compliance/common/helper.py
- terraform_compliance/steps/steps.py
- tests/terraform_compliance/common/test_helper.py
This PR is addressing the issue reported in #171
> Fixed a problem where only first resource found were reported

- README.md
I seriously did not know what Radish was before today. This is also my first time using anything based on Gherkin. My first instinct was to write files with extension `.txt` and put scenarios in them without defining features first.
> Link to Radish in the readme

- CHANGELOG.md
- terraform_compliance/common/error_handling.py
- terraform_compliance/extensions/ext_radish_bdd.py
- terraform_compliance/extensions/silent_formatter.py
- terraform_compliance/main.py
Improved silent mode (`-S`) with better output and formatting
Note that '-silent' flag doesn't work, contrary to what docs suggest, neither in master or this branch.
> Silent Formatting

- Dockerfile
> Disable ssh host key checking for private repositories

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general-question.md
This PR changes some formatting in the issue templates and adds a few comments on how to make a bug report.
> Improve issue templates

- terraform_compliance/extensions/terraform.py
> Add support for Terraform 1.3.*

- setup.py
> Loosen dependencies

- terraform_compliance/extensions/terraform.py
> Add support for Terraform 1.4.*

- terraform_compliance/extensions/terraform.py
Apologies for submitting a PR for a typo, but it appears in a fairly common error message and so felt worth fixing.
> Fixed typo in error message

- terraform_compliance/extensions/terraform.py
> Support for Terraform 1.7

- terraform_compliance/extensions/terraform.py
> Add support for Terraform version 1.11

- terraform_compliance/extensions/terraform.py
> Add support for Terraform version 1.12
