terraform-compliance/cli

radish/steps.py, requirements.txt
The latest versions of radish-bdd have changed `arg_expr` to `custom_type`, which caused the included example code to fail.
=> Fix arg_expr error caused by latest version of radish-bdd and pin requirements to supported versions.

terraform_compliance/common/pyhcl_helper.py, terraform_compliance/common/readable_dir.py, terraform_compliance/main.py, terraform_compliance/steps/steps.py, tests/terraform_compliance/test_main.py
There was a problem on `0.3.7` on application initiation where it was forgotten for a specific case. In `0.3.8` it is fixed and working properly. 
*`0.3.7` was not working at all!*
Fixed several cases in steps where reading a value via regex and drilling down into the tf configuration was failing when drilled down entity is either a Resource or Property.
=> Fixed an unstable version

terraform_compliance/main.py, terraform_compliance/steps/__init__.py
the example01/aws/tags.feature was failing when I had a null_resource (which doesn't support tags). Seems pretty trivial, please be kind :)
=> Added null_resource to untaggable resources

terraform_compliance/common/exceptions.py, terraform_compliance/common/pyhcl_helper.py, terraform_compliance/main.py, terraform_compliance/steps/steps.py, tests/terraform_compliance/common/test_pyhcl_helper.py
On scenarios where 
```
... it <condition> contains <something>
```
is used, if the data is being processed is an HCL value, this PR will parse that value and additionally search for `<something>` existing within the keys of that value.
This PR addresses the issue reported in #48
=> Fixes a problem where tags are not working properly

README.md, example/example_01/aws/credentials.feature, example/example_01/aws/encryption_in_flight.feature, example/example_01/aws/naming_standards.feature, example/example_01/aws/security_groups.feature, example/example_01/aws/tags.feature, requirements.txt, terraform_compliance/common/helper.py, terraform_compliance/extensions/ext_radish_bdd.py, terraform_compliance/main.py, terraform_compliance/steps/steps.py, tests/mocks.py, tests/terraform_compliance/extensions/test_ext_radish_bdd.py, tests/terraform_compliance/steps/test_given_steps.py, tests/terraform_compliance/steps/test_main_steps.py
This release will address problems reported in ;
- #58 
- #57 
It also includes ;
- General stability and integrity refactoring
- Scenario skipping where if`GIVEN` and `WHEN` failed during the tests, further steps won't be run. 
- Additional information about failures, scenario skips or resource filtering cases.
- Additional documentation ( although I will create a separate web page for the tool soon ) about steps, general structure and list of the steps that are available with examples
- Upstream functionality fix on `radish-bdd` that leads library upgrade from `0.8.6` to `0.10.0` within the tool.
- All examples updated based on the new step structure
**THIS VERSION MAY NOT BE COMPATIBLE WITH 0.4 VERSIONS**
Some of the step definitions and style of drilling down the terraform code might …
=> Skipping, new informations and general integrity fixes

terraform_compliance/main.py, terraform_compliance/steps/steps.py
Step definition decorator was declared with wrong variable types leading `cidr` definitions translated as one character - which was failing Security Groups
=> Fixed CIDR definition in the steps 

README.md, example/example_01/aws/security_groups.feature, terraform_compliance/common/helper.py, terraform_compliance/main.py, terraform_compliance/steps/steps.py, tests/terraform_compliance/common/test_helper.py, tests/terraform_compliance/steps/test_main_steps.py
Currently Security Group Rule validation can do "must not have" for individual ports and port ranges.
This pull request will implement "must only have" condition for security group rule with ports defined as comma delimited values.
=> New Feature - Security Group Rule It must only have condition

requirements.txt, terraform_compliance/main.py, terraform_compliance/steps/__init__.py
* Upgraded `radish-bdd` from 0.10.0 to 0.11.1
* Added `random_string` as a untaggable resource. (#67)
* Addresses the problem identified in #79.
=> Upgraded radish-bdd, added a new untaggable resource.

.travis.yml, Dockerfile.template, setup.py, terraform_compliance/common/helper.py, terraform_compliance/extensions/ext_radish_bdd.py, terraform_compliance/extensions/terraform_validate.py, terraform_compliance/main.py, terraform_compliance/steps/steps.py, tests/terraform_compliance/common/test_pyhcl_helper.py, tests/terraform_compliance/extensions/test_ext_radish_bdd.py, tests/terraform_compliance/steps/test_main_steps.py, tests/terraform_compliance/test_main.py
Hi, I am looking to use this tool for a shared modules repository I am working on for our company.  I noticed that you are still using python 2.7 and decided to take a crack at upgrading to python 3.x.  All tests pass on my machine, and there weren't many things that needed to get changed.
=> Upgrade to use python 3.

terraform_compliance/main.py, terraform_compliance/steps/__init__.py
aws_lb_listener is an untaggable resource.
=> adding aws_lb_listener to the list of untaggable_resources

CHANGELOG.md, Dockerfile.template, terraform_compliance/main.py
Relates to
https://github.com/eerkunt/terraform-compliance/issues/102
When developing on a non-Linux system (such as Mac OS), the terraform binary cannot be mounted into the container from the host as it is not compiled for the same OS.
I understand this might not be the best way to handle this...
=> Include Terraform in the container

example/example_01/aws/encryption_at_rest.feature, example/example_01/aws/encryption_in_flight.feature, terraform_compliance/main.py, terraform_compliance/steps/steps.py
Step `And its value must not match the "\x00" regex` is passed even though the property value in plan is null.
so, I changed the code in steps.py and replaced line#377
` if values['values'] is None and regex == '\x00' and condition == 'must not':`
with
` if values['values'] is None and regex == 'null' and condition == 'must not':`
and the rule worked as expected.
=> regex =='\x00' if condition fails when the input regex is euqal to \x00

terraform_compliance/extensions/terraform.py, tests/terraform_compliance/extensions/test_terraform.py
I've run into a couple of situations where non-compliant resources are not caught because they don't show up in the `planned_changes` block of the output file. Parsing the `resource_changes` block in the terraform plan output seems to fix the issue. Seems like this was something that was planned anyway from the TODO.
=> Support parsing resource changes in plan

terraform_compliance/common/helper.py, terraform_compliance/extensions/terraform.py, terraform_compliance/steps/steps.py, tests/terraform_compliance/common/test_helper.py, tests/terraform_compliance/extensions/test_terraform.py
As also reported in #168, a problem exists where resource mounting and recursive searching were causing a problem on `resources that support tags` where we should not either do recursive searching or resource mounting.
This PR will disable resource mounting on scenarios where `resources that support tags` are used.
=> Resource mounting problems on resource that supports tags

CHANGELOG.md, terraform_compliance/common/helper.py, terraform_compliance/extensions/terraform.py, terraform_compliance/steps/steps.py, tests/mocks.py, tests/terraform_compliance/steps/test_main_steps.py
`terraform-compliance` was failing to test properly while having multiple provider definitions or provider aliases, also reported in #173
This problem adds this capability while fixing the issue.
=> Support for provider aliases and multiple provider definitions.

terraform_compliance/steps/steps.py
As reported in #242, this PR resolves a problem where `count` function within the steps counts the number of characters in a `str`, `int` or `bool` variable.
=> Fixed a problem on count function 

docs/pages/bdd-references/when.md
For both `is` and `is not` I have added reference that `type` references the Terraform resource type as this is very useful to know and wasn't clear from the documentation. I've tidied up the descriptions around those too (not requiring "e.g" in the description when it's a separate column). Whilst doing this I also fixed two spelling mistakes and capitalised "Terraform" when referring to the program and not the command line.
=> Add reference for type an minor corrections

requirements.txt, terraform_compliance/extensions/terraform.py, tests/terraform_compliance/extensions/test_terraform.py
This PR addresses the problem described in #257.
Resource addresses starting with `data` was causing a problem where it was misinterpreted as a `data` entity, even though they are native resources.
=> Fixed a problem where resource names starting with 'data' was misinterpreted

CHANGELOG.md, docs/pages/usage/index.md, terraform_compliance/main.py
Completes #218 
Users may wish to reference a specific branch or directory in remote git repositories. This allows them to do this with syntax similar to Terraform [Modules in Package Sub-directories](https://www.terraform.io/docs/modules/sources.html#modules-in-package-sub-directories).
The reference must include `//` after `.git` and end with `?ref=<branch-name>` or `?ref=<tag>`.
```
[~] $ terraform-compliance -f git:ssh://github.com/user/repo.git//directory?ref=v1.0.0 ...
```
The directory is optional.
```
[~] $ terraform-compliance -f git:ssh://github.com/user/repo.git//?ref=staging ...
```
Note that commit hashes are not supported.
=> Enhancement: Add directory and branch support for -f parameter for remote git repos

terraform_compliance/common/error_handling.py
Addresses #271 
Previously, step.failure.traceback was always set to None. This was breaking --junit-xml flag. Now, the default traceback is "No Traceback" and it gets replaced by the failure's name and message.
=> Added better failure traceback for junit-xml dumps

docs/pages/bdd-references/then.md, terraform_compliance/common/helper.py, terraform_compliance/steps/then/its_value_condition_match_the_search_regex.py, tests/functional/test_issue-285/.expected, tests/functional/test_issue-285/.unexpected, tests/functional/test_issue-285/main.tf, tests/functional/test_issue-285/test.feature
which prevents causing type errors attempting to iterate through a non-iterable.
Addresses issue #285 
Also added float to its_value_condition_match_the_search_regex.py, because it was included on other places and made sense. (not tested)
=> Small bugfix on seek_value_in_dict

CHANGELOG.md, requirements.txt, setup.py, terraform_compliance/common/defaults.py, terraform_compliance/common/helper.py, terraform_compliance/extensions/terraform.py, terraform_compliance/main.py, tests/terraform_compliance/common/test_helper.py
* Implemented `python_version_check` to ensure minimum supported Python version is 3.6.0
=> Python version check

CHANGELOG.md, docs/pages/usage/index.md, requirements.txt, setup.py, terraform_compliance/main.py, terraform_compliance/steps/terrain.py
This option will let you peek in the stash or run IPython on the current step.
**Commands**
- s: prints stash
- d: opens Interactive Python.
- h: prints commands
In Python shell, context can be accessed via `step.context.stash`. Note that modifications to step object will carry over to the steps below.
It is usually a better idea to inspect the stash *before* the step being debugged.
- I was hoping to have an interactive and colorful way of parsing the stash, but this was the solution I could come up with. 
- Curses can be added to run the commands with a single click instead of pressing enter afterwards. However, I would need help to prevent curses from clearing the screen. (Which I is probably not easy)
=> Live debugging

CHANGELOG.md, terraform_compliance/main.py, terraform_compliance/steps/terrain.py
Use `world.config.user_data` instead of using global variables
=> Debugging refactor

terraform_compliance/extensions/terraform.py, tests/terraform_compliance/common/test_helper.py, tests/terraform_compliance/extensions/test_terraform.py
Based on the failures we were having and the file unexpectedly trying to process random nested structures that happened to be named "resources" I have attempted to address this.
I used the information at [JSON Output Format](https://www.terraform.io/docs/internals/json-format.html#configuration-representation) to determine that the "resources" should be directly below the "root_module" in the configuration. Please let me know if this is an incorrect assumption.
=> Nested structure problem fix

CHANGELOG.md, terraform_compliance/common/helper.py, terraform_compliance/extensions/terraform.py, tests/terraform_compliance/extensions/test_terraform.py
Large plan files with lots of references may take too much time to mount.
Following is an attempt to reduce it. (Processing my plan file went from taking 90 seconds to 4 seconds)
Using `raw_resources` instead of `resources` to prevent having too much information within the resources. (i.e. discard nested mountings and cycle references)
I believe cycle referencing shouldn't be a problem. Older versions don't seem to fully support it, so I won't either. [Example](https://github.com/eerkunt/terraform-compliance/compare/master...Kudbettin:slow_mounting) of how cycle references could be handled. (Changes the application behavior a bit.)
=> Faster mounting

CHANGELOG.md, terraform_compliance/common/error_handling.py
Fixed an issue where the null character in step definition is breaking `--junit-xml` dump.
Note that non '\x00' chars that are not XML compatible could still break the flag `--junit-xml`. However, I'm 70% sure terraform doesn't let you use XML incompatible characters, so it should be enough to replace the ones we provide.
Addresses #345
=> Replace the null byte in failure traceback to prevent XML dump from breaking

docs/pages/Examples/restrict_resource_creation.md
Fix the example in [docs/examples](https://terraform-compliance.com/pages/Examples/restrict_resource_creation.html) as mentioned in #339
=> docs: "Ensure some resource types are always created"

terraform_compliance/common/error_handling.py
Clean up x08 character which is breaking JUnit XML conversion during provider version_constraint checks (character is present on back of provider name string).
=> Update error_handling.py for x08 character

terraform_compliance/common/helper.py
**Current merging policy:**
<pre>
assume target is low priority
conflicts
regular values: higher prio overrides
dictionaries: merge conflicting dictionaries
lists: higher prio overrides for regular values, merge any matching dictionary/list elements
if len(target) > len(source):
<b>drop the tail</b>
</pre>
**New merging policy:**
<pre>
assume target is low priority
conflicts
regular values: higher prio overrides
dictionaries: merge conflicting dictionaries
lists: higher prio overrides for regular values, merge any matching dictionary/list elements
if len(target) > len(source):
<b>append the tail to the source</b>
</pre>
#428 should be resolved before merging this.
=> dict_merge change for issue 428

CHANGELOG.md, Dockerfile
Update docker image to python:3.7.10-slim. Note that python:3.7.10 is based on buster whereas python:3.7.3 was based on stretch.
=> Update docker image to python:3.7.10-slim

docs/pages/usage/index.md
It's listed in the details but not the initial section
=> Add missing --terraform option to docs

docs/pages/usage/index.md
It worked fine for a https source when I had already got the credentials available in the configured git credential manager
=> Note that https git source can be used for private repos if configured

CHANGELOG.md, terraform_compliance/common/readable_plan.py
This PR will fixes some edge cases where `.splitlines()` fails on complicated JSON files. 
Additionaly, we switched from slow native `json` library to `orjson` library. That will increase the performance on very large plan files.
=> Fixing a problem while reading the plan

README.md, docs/pages/installation/pip.md, setup.py, terraform_compliance/common/helper.py, terraform_compliance/common/readable_plan.py
Use it if available for faster parsing but for those less keen on using
a multi stage docker build and ensuring they have the correct shared
library dependencies (particularly challenging if building off an alpine
container that doesn't use a distribution build) they can avoid the
extra_requirement.
=> Move orjson to be an optional dependency

docs/pages/Examples/AWS/security_groups.md, docs/pages/Examples/AWS/tags_related.md, docs/pages/Examples/AWS/vpc_peering.md, docs/pages/Examples/Azure/naming_standards.md, docs/pages/bdd-references/then.md, docs/pages/bdd-references/when.md
Add explanation on why [When it contains](https://terraform-compliance.com/pages/bdd-references/when.html#when-it-contains-something) is discouraged and what to use instead.
Remove instances of [When it contains](https://terraform-compliance.com/pages/bdd-references/when.html#when-it-contains-something) from examples to prevent encouraging the usage of it.
=> Encourage the usage of when it has

docs/pages/Examples/AWS/tags_related.md
Updating examples to reflect the supportability of the tags_all readonly attribute for aws terraform providers
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#propagating-tags-to-all-resources
Also quoting the <tags> variable placeholder as tags keys that have spaces break terraform compliance
Addresses #544
=> Update tags examples to expand to tags_all

terraform_compliance/__main__.py
I expected to be able to do `python -m terraform_compliance` as we would with pip or other python tools, but it didn't work. Instead I had to do `python -m terraform_compliance.main`.
This fixes that problem.
=> Simplify support for running module directly

terraform_compliance/common/error_handling.py
Hi @eerkunt,
In [1.3.35](https://github.com/terraform-compliance/cli/compare/1.3.34...1.3.35#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L17) external `mock` module was removed from the dependency list, but the import wasn't updated in `common/error_handling.py` where it's requested. This predictably results in `No module named 'mock'` error.
This PR fixes the import statement.
Cheers!👍
=> fix: replace mock module with unittest.mock

setup.py
Mock is a needed dependency of terraform-compliance used in terraform_compliance.common.error_handling
With last release of terraform-compliance (1.3.37) our ci jobs are failing due to the import issue:
```
! ERROR: Unable to import module 'steps' from '/usr/local/lib/python3.10/dist-packages/terraform_compliance/steps/steps.py': No module named 'mock'
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/radish/loader.py", line 43, in load_module
spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/usr/local/lib/python3.10/dist-packages/terraform_compliance/steps/steps.py", line 14, in <module>
from …
```
=> fix(setup): add mock as dependency

docs/pages/bdd-references/index.md, docs/pages/bdd-references/using_tags.md, docs/pages/ci-cd/circle_ci.md, docs/pages/ci-cd/github_actions.md, docs/pages/ci-cd/index.md, docs/pages/contribution/index.md
Fixes #718
Closes #718
Provide some documentation on how a developer might integrate Terraform Compliance into a CircleCI pipeline and GitHub Actions.
Plus some minor changes for effect -> affect.
=> Add documentation for CircleCI and GitHub Actions integrations

terraform_compliance/__main__.py, terraform_compliance/main.py
We've found that terraform compliance failures were not causing our builds to fail
We call terraform compliance using `python -m terraform_compliance`
I believe it works fine for the .exe mode since that calls `cli` directly and will handle the exit code from that automatically
=> Return system exit code when running as module

docs/pages/bdd-references/index.md
I think Radish BDD changed their domain/URL at some point and someone took it over. So the current URL referenced in docs leads to a shady website and is the incorrect URL. Fixing to correct URL.
=> Update incorrect radish-bdd website URL
